---
- name: Get software for apt repository management.
  apt:
    state: present
    name:
      - python3-apt
      - python3-pycurl

- name: Add ondrej repository for later versions of PHP.
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: "Install Apache, MySQL, PHP, and other dependencies."
  apt:
    state: present
    name:
      - acl
      - git
      - curl
      - unzip
      - sendmail
      - apache2
      - php8.1-common
      - php8.1-cli
      - php8.1-dev
      - php8.1-gd
      - php8.1-curl
      - php8.1-opcache
      - php8.1-xml
      - php8.1-mbstring
      - php8.1-pdo
      - php8.1-mysql
      - php8.1-apcu
      - libpcre3-dev
      - libapache2-mod-php8.1
      - python3-mysqldb
      - mysql-server

- name: Disable the firewall (since this is for local dev only).
  service: name=ufw state=stopped

- name: "Start Apache, MySQL, and PHP."
  service: "name={{ item }} state=started enabled=yes"
  with_items:
    - apache2
    - mysql
