---
- name: Ensure Kirby directory exists.
  file:
    path: "{{ kirby_core_path }}"
    state: directory
    owner: www-data
    group: www-data

- name: Check if Kirby project already exists.
  stat:
    path: "{{ kirby_core_path }}/composer.json"
  register: kirby_composer_json

- name: Create Kirby project.
  composer:
    command: create-project
    arguments: "{{ kirby_kit }} {{ kirby_core_path }}"
    working_dir: "{{ kirby_core_path }}"
    no_dev: true
  become_user: www-data
  when: not kirby_composer_json.stat.exists
